### ISSUE TITLE
any performance comparisons or benchmarks?

### ISSUE THREAD

**Issue by damian-666** [ebatianoSoftware/Farseer-Physics-Standard#1]
I came across this article below and this looks promising at least in some platfroms even w vector2, 3 and 4,  but i have a custom fork and a few questions.

did you make any tests comparisons like stacking 100 bullets?   or triangulate large concave body?  simple comparisons?  are we seeing anything close to  2, or 4x improvement ?    the monogame community ddint report anything noticiable but i doubt it matters in MG.. its just passing stuff to GPU and doesnt have vector  complex algorithms internally.

 its only my physics code especially CCD that can get slow.. and triangulation... etc.. i have to copy vectors to graphics anywasy because i used the Farseer version of vector2d and make it persistent.  so  if u think this was worth it id love to diff the code and consider it...  Velcro and Aether were the only canonical branches , and Aether is slightly active but lots of monogame indies use forks of it.  Thanks for making this btw.

https://praeclarum.org/2019/10/15/vector-performance.html

i looked at that diffs butg it looks like the baseline isnt included so I cant see how likely regression would be..   But did you use a sort of script to generate this code?   seems like that would be the way to do it...   then it can be run over anyones fork..

**Comment by ebatiano** [comment]
No, I haven't done any performance comparsions nor benchmarks. The reason of doing this was not to improve performance (which would be of course great if there is any), but just to get rid of MonoGame dependency and make it pure .NETStandard library.

About how it was done, it was done by hand. I removed all MonoGame namespaces (actually Microsoft.Xna.Framework) and the put Numerics.Vectors there. Also some operators were not implemented in Numerics, so I needed to change their usages to proper method calls.

I got rid of examples and other stuff that was written in MonoGame and was not a part of physics functionality.

**Comment by ebatiano** [comment]
> i looked at that diffs butg it looks like the baseline isnt included so I cant see how likely regression would be.. But did you use a sort of script to generate this code? seems like that would be the way to do it... then it can be run over anyones fork..

Actually I couldn't find Farseer on github (now I see there's [VelcroPhysics](https://github.com/Genbox/VelcroPhysics) avaliable), so I took the latest version from CodePlex I think.

**Comment by damian-666** [comment]
Thanks for answering..i see people doing crazy 128 wifde.lane using structs and very cache conscious and adding special intrinsic code  and getting  mixed results bit it's mind boggling work and frankly seems like premature optimizations that should go into .net   but if matrix and vector 3 and 2 and that guys results in the link are true to just get 2 or 3x boost. ..  well then i might check it..  and report to u.   monogame guys didn't find an improvement but don't have complex algorithms.  Velcro Is the latest maintsinef and i have an early fork that good enough and heavily modified. 






 I'm wondering how long it took u to do it.manually?      Btw now use monogame and love it...but before i used the farseer namespace.    My farseer is build as NetStandard using the farseer xna not linked to any graphics.  But  I also have NetStandard graphics  libraries  shared  for all my platfroms linked to monogame as open gl.      Then the net 6  console windowd clients linked to monogame DX actually target the 
windows platform so its the exe that choose DirectX or Gl .    there is a Android sample and does this as well.. so monogame modules can be NetStandard but the exe must link and compile the content which can be shared.   It's a bit tricky but

**Comment by damian-666** [comment]
It u are interested I'll find the android template how to use NetStandard w monogame using open gl just to make it compile.. for any platfrom but no repeat code  or assets and thin exes.. it's rough but Im now a appreciating it. And didn't Wana go w unity

**Comment by ebatiano** [comment]
> I'm wondering how long it took u to do it.manually?
Actually not so long - as I said I just used tool to Fing/Replace Microsoft.Xna.Framework with System.Numerics, then replaced Matrix with Matrix3x2 from numericsm and fixed couple of places where Numerics' Vector2 and Matrix3x2 had different api for some operations (like multiplying).
Of course I am talking only about core funionality, as I didn't port any samples and other more MonoGame dependent stuff.

**Comment by damian-666** [comment]
if u are curious to know i timed it with the help of the new c# feature  global using , shared test code, one test, linked to your fork and to my xna fork,  and i found some significant performance different on order of 2, 3x faster on one of my tests , but one 
 that doesnt allocate vector2 or even use the farseer methods..   just adding up  and normalizing random vector2s.   both struct are the same size but i read some buzz on the dotnet core t about this issue that its not always faster.    i spit out the total to make sure that code isnt optimzed away.   as as far as the physics engine im not sure yet if simply usnig the new vec and matrix will give it cheap boost ... decompose doesnt benefit nor does TOI...  def looks like it should be explored tho.. Thanks for making this..     definitely surprised me to see it more than 2x faster on normalize and add...
